// /script/products.js

// ATENÇÃO: A estrutura de dados foi totalmente revisada e corrigida.
export const products = [
    { id: 1, type: 'tradicional', name: 'Copo Tradicional 200ml', currentPrice: 10.00, image: 'img/produtos/acai_200.jpg', customizable: true, addons: [ { title: 'Frutas', rule: { type: 'max', count: 1 }, items: [ { name: 'Banana', price: 0 }, { name: 'Morango', price: 0 }, { name: 'Manga', price: 0 }, { name: 'Uva', price: 0 } ] }, { title: 'Adicionais', rule: { type: 'special_charge', freeLimit: 2, extraPrice: 2.00 }, items: [ { name: 'Confete', price: 0 }, { name: 'Leite Condensado', price: 0 }, { name: 'Granola', price: 0 }, { name: 'Sucrilhos', price: 0 }, { name: 'Leite em Pó', price: 0 }, { name: 'Paçoca', price: 0 }, { name: 'Amendoim', price: 0 }, { name: 'Mel', price: 0 }, { name: 'Bala de goma', price: 0 }, { name: 'Banana', price: 0 } ] } ] },
    { id: 2, type: 'tradicional', name: 'Copo Tradicional 300ml', currentPrice: 14.00, image: 'img/produtos/acai_300.jpg', customizable: true, addons: [ { title: 'Frutas', rule: { type: 'max', count: 1 }, items: [ { name: 'Banana', price: 0 }, { name: 'Morango', price: 0 }, { name: 'Manga', price: 0 }, { name: 'Uva', price: 0 } ] }, { title: 'Adicionais', rule: { type: 'special_charge', freeLimit: 2, extraPrice: 2.00 }, items: [ { name: 'Confete', price: 0 }, { name: 'Leite Condensado', price: 0 }, { name: 'Granola', price: 0 }, { name: 'Sucrilhos', price: 0 }, { name: 'Leite em Pó', price: 0 }, { name: 'Paçoca', price: 0 }, { name: 'Amendoim', price: 0 }, { name: 'Mel', price: 0 }, { name: 'Bala de goma', price: 0 }, { name: 'Banana', price: 0 } ] } ] },
    { id: 3, type: 'tradicional', name: 'Copo Tradicional 400ml', currentPrice: 17.00, image: 'img/produtos/acai_400.jpg', customizable: true, addons: [ { title: 'Frutas', rule: { type: 'max', count: 1 }, items: [ { name: 'Banana', price: 0 }, { name: 'Morango', price: 0 }, { name: 'Manga', price: 0 }, { name: 'Uva', price: 0 } ] }, { title: 'Adicionais', rule: { type: 'special_charge', freeLimit: 2, extraPrice: 2.00 }, items: [ { name: 'Confete', price: 0 }, { name: 'Leite Condensado', price: 0 }, { name: 'Granola', price: 0 }, { name: 'Sucrilhos', price: 0 }, { name: 'Leite em Pó', price: 0 }, { name: 'Paçoca', price: 0 }, { name: 'Amendoim', price: 0 }, { name: 'Mel', price: 0 }, { name: 'Bala de goma', price: 0 }, { name: 'Banana', price: 0 } ] } ] },
    { id: 4, type: 'tradicional', name: 'Copo Tradicional 700ml', currentPrice: 27.00, image: 'img/produtos/acai_700.jpg', customizable: true, addons: [ { title: 'Frutas', rule: { type: 'max', count: 1 }, items: [ { name: 'Banana', price: 0 }, { name: 'Morango', price: 0 }, { name: 'Manga', price: 0 }, { name: 'Uva', price: 0 } ] }, { title: 'Adicionais', rule: { type: 'special_charge', freeLimit: 2, extraPrice: 2.00 }, items: [ { name: 'Confete', price: 0 }, { name: 'Leite Condensado', price: 0 }, { name: 'Granola', price: 0 }, { name: 'Sucrilhos', price: 0 }, { name: 'Leite em Pó', price: 0 }, { name: 'Paçoca', price: 0 }, { name: 'Amendoim', price: 0 }, { name: 'Mel', price: 0 }, { name: 'Bala de goma', price: 0 }, { name: 'Banana', price: 0 } ] } ] },
    {
        id: 9, type: 'tradicional', name: 'Copo Levanta', description: 'Uma bomba de energia para o seu dia!', currentPrice: 12.00, image: 'img/produtos/acai_levanta.jpg',
        customizationType: 'levanta', customizable: true,
        sizes: [ { name: '300ml', price: 12.00 }, { name: '500ml', price: 15.00 }, { name: '700ml', price: 18.00 }, { name: '1 Litro', price: 27.00 } ],
            addons: [
    { title: 'Frutas', rule: { type: 'any', displayText: '(+R$2,00 por item)' }, items: [ { name: 'Morango', price: 2.00 }, { name: 'Banana', price: 2.00 },] },
            { title: 'Adicionais', rule: { type: 'any', displayText: '(Leite em Pó e Leite Condensado +R$2,00 cada)' }, items: [ { name: 'Paçoca', price: 0 }, { name: 'Leite', price: 0 }, { name: 'Leite em Pó', price: 2.00 }, { name: 'Leite Condensado', price: 2.00 },] }
        ]
    },
    // --- PRODUTOS TRUFADOS ---
    { id: 5, type: 'trufado', name: 'Copo Trufado 200ml', description: 'Com deliciosa camada de trufa.', currentPrice: 12.00, image: 'img/produtos/acai_trufado_200.jpg', customizable: true, addons: [ { title: 'Trufados', rule: { type: 'max', count: 1 }, items: [ { name: 'Amendoim', price: 0 }, { name: 'Laka Oreo', price: 0 }, { name: 'Sensação', price: 0 }, { name: 'Ninho', price: 0 }, { name: 'Brigadeiro', price: 0 }, { name: 'Chocolate Branco', price: 0 }, { name: 'Nutella', price: 0 }, { name: 'Ovomaltine', price: 0 } ] }, { title: 'Frutas', rule: { type: 'special_charge', freeLimit: 1, extraPrice: 2.00, displayText: '(1 Grátis) Adicional +R$2,00' }, items: [ { name: 'Banana', price: 0 }, { name: 'Morango', price: 0 }, { name: 'Manga', price: 0 }, { name: 'Uva', price: 0 } ] } ] },
    { id: 6, type: 'trufado', name: 'Copo Trufado 300ml', description: 'A combinação perfeita de açaí e trufa.', currentPrice: 16.00, image: 'img/produtos/acai_trufado_300.jpg', customizable: true, addons: [ { title: 'Trufados', rule: { type: 'max', count: 1 }, items: [ { name: 'Amendoim', price: 0 }, { name: 'Laka Oreo', price: 0 }, { name: 'Sensação', price: 0 }, { name: 'Ninho', price: 0 }, { name: 'Brigadeiro', price: 0 }, { name: 'Chocolate Branco', price: 0 }, { name: 'Nutella', price: 0 }, { name: 'Ovomaltine', price: 0 } ] }, { title: 'Frutas', rule: { type: 'special_charge', freeLimit: 1, extraPrice: 2.00, displayText: '(1 Grátis) Adicional +R$2,00' }, items: [ { name: 'Banana', price: 0 }, { name: 'Morango', price: 0 }, { name: 'Manga', price: 0 }, { name: 'Uva', price: 0 } ] } ] },
    { id: 7, type: 'trufado', name: 'Copo Trufado 400ml', description: 'Mais açaí e muito mais trufa.', currentPrice: 22.00, image: 'img/produtos/acai_trufado_400.jpg', customizable: true, addons: [ { title: 'Trufados', rule: { type: 'max', count: 1 }, items: [ { name: 'Amendoim', price: 0 }, { name: 'Laka Oreo', price: 0 }, { name: 'Sensação', price: 0 }, { name: 'Ninho', price: 0 }, { name: 'Brigadeiro', price: 0 }, { name: 'Chocolate Branco', price: 0 }, { name: 'Nutella', price: 0 }, { name: 'Ovomaltine', price: 0 } ] }, { title: 'Frutas', rule: { type: 'special_charge', freeLimit: 1, extraPrice: 2.00, displayText: '(1 Grátis) Adicional +R$2,00' }, items: [ { name: 'Banana', price: 0 }, { name: 'Morango', price: 0 }, { name: 'Manga', price: 0 }, { name: 'Uva', price: 0 } ] } ] },
    { id: 8, type: 'trufado', name: 'Copo Trufado 700ml', description: 'A experiência suprema de açaí e trufa.', currentPrice: 36.00, image: 'img/produtos/acai_trufado_700.jpg', customizable: true, addons: [ { title: 'Trufados', rule: { type: 'max', count: 1 }, items: [ { name: 'Amendoim', price: 0 }, { name: 'Laka Oreo', price: 0 }, { name: 'Sensação', price: 0 }, { name: 'Ninho', price: 0 }, { name: 'Brigadeiro', price: 0 }, { name: 'Chocolate Branco', price: 0 }, { name: 'Nutella', price: 0 }, { name: 'Ovomaltine', price: 0 } ] }, { title: 'Frutas', rule: { type: 'special_charge', freeLimit: 1, extraPrice: 2.00, displayText: '(1 Grátis) Adicional +R$2,00' }, items: [ { name: 'Banana', price: 0 }, { name: 'Morango', price: 0 }, { name: 'Manga', price: 0 }, { name: 'Uva', price: 0 } ] } ] },

    // --- PRODUTOS CACHORRO-QUENTE ---
    { id: 10, type: 'hotdog', name: 'Cachorro-quente simples', description: '1 salsicha, maionese, vinagrete, batata palha, ketchup e mostarda', currentPrice: 13.00, image: 'img/produtos/hotdog_1.jpg', customizable: true, addons: [ { title: 'Acompanhamentos', rule: { type: 'any', displayText: '(+R$2,00 cada)' }, items: [ { name: 'Cheddar', price: 2.00 }, { name: 'Catupiry', price: 2.00 } ] }  ] },
    { id: 11, type: 'hotdog', name: 'Cachorro-quente duplo', description: '2 salsichas, maionese, vinagrete, batata palha, ketchup e mostarda', currentPrice: 15.00, image: 'img/produtos/hotdog_2.jpg', customizable: true, addons: [ { title: 'Acompanhamentos', rule: { type: 'any', displayText: '(+R$2,00 cada)' }, items: [ { name: 'Cheddar', price: 2.00 }, { name: 'Catupiry', price: 2.00 } ] } ] },
    { id: 12, type: 'hotdog', name: 'Cachorro-quente pão francês', description: '1 salsicha, maionese, vinagrete, batata palha, ketchup e mostarda', currentPrice: 13.00, image: 'img/produtos/hotdog_3.jpg', customizable: true, addons: [ { title: 'Acompanhamentos', rule: { type: 'any', displayText: '(+R$2,00 cada)' }, items: [ { name: 'Cheddar', price: 2.00 }, { name: 'Catupiry', price: 2.00 } ] } ] },
    { id: 13, type: 'hotdog', name: 'Cachorro-quente duplo no pão francês', description: '2 salsichas, maionese, vinagrete, batata palha, ketchup e mostarda', currentPrice: 15.00, image: 'img/produtos/hotdog_4.jpg', customizable: true, addons: [ { title: 'Acompanhamentos', rule: { type: 'any', displayText: '(+R$2,00 cada)' }, items: [ { name: 'Cheddar', price: 2.00 }, { name: 'Catupiry', price: 2.00 } ] } ] },
    { id: 18, type: 'hotdog', name: 'Cachorro-quente baguete', description: '2 salsichas, maionese, vinagrete, batata palha, ketchup e mostarda', currentPrice: 18.00, image: 'img/produtos/hotdog_5.jpg', customizable: true, addons: [ { title: 'Acompanhamentos', rule: { type: 'any', displayText: '(+R$2,00 cada)' }, items: [ { name: 'Cheddar', price: 2.00 }, { name: 'Catupiry', price: 2.00 } ] } ] },

    // --- PRODUTOS CALDOS ---
    { id: 14, type: 'caldo', name: 'Caldos', description: 'Escolha seu sabor e tamanho.', currentPrice: 9.00, image: 'img/produtos/caldo.jpeg', customizable: true, customizationType: 'caldo', sizes: [ { name: '240ml', price: 9.00 }, { name: '360ml', price: 14.00 }, { name: '480ml', price: 18.00 } ] },
];